# Copy to config/ae2-tag-preferences-client.toml for Star Technology.
presets = [
    "gtceu:circuits/ulv=kubejs:ulv_universal_circuit",
    "gtceu:circuits/lv=kubejs:lv_universal_circuit",
    "gtceu:circuits/mv=kubejs:mv_universal_circuit",
    "gtceu:circuits/hv=kubejs:hv_universal_circuit",
    "gtceu:circuits/ev=kubejs:ev_universal_circuit",
    "gtceu:circuits/iv=kubejs:iv_universal_circuit",
    "gtceu:circuits/luv=kubejs:luv_universal_circuit",
    "gtceu:circuits/zpm=kubejs:zpm_universal_circuit",
    "gtceu:circuits/uv=kubejs:uv_universal_circuit",
    "gtceu:circuits/uhv=kubejs:uhv_universal_circuit",
    "gtceu:circuits/uev=kubejs:uev_universal_circuit",
    "gtceu:circuits/uiv=kubejs:uiv_universal_circuit",
    "gtceu:circuits/uxv=kubejs:uxv_universal_circuit"
]

enableAudit = true
